name: Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - uses: actions/cache@v2
      id: cache-poetry
      with:
        path: ~/.cache/pip
        key: ${{ hashFiles('pyproject.toml') }}
    - name: Install poetry
      if: steps.cache-poetry.outputs.cache-hit != 'true'
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - uses: actions/cache@v2
      id: cache-dependencies
      with:
        path: ~/.cache/pypoetry
        key: ${{ hashFiles('poetry.lock') }}
    - name: Install dependencies
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: poetry install
    - name: Lint
      run: make lint