name: Upload Python Package

on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup PDM
      uses: pdm-project/setup-pdm@v4
      with:
        cache: true
    - name: Install dependencies
      run: pdm install
    - name: Build and publish
      env:
        PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        pdm publish -u __token__ -p $PYPI_PASSWORD