name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - uses: actions/cache@v2
      id: cache
      with:
        path: ~/.cache/pypoetry
        key: ${{ hashFiles('poetry.lock') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: poetry install
    - name: Test
      run: |
        make test
        poetry run coverage xml
    - name: Report coverage
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
